### ISSUE TITLE
Idea: Make it more clear that the data is for a specific hour in the tweet

### ISSUE THREAD

**Issue by madsnedergaard** [Robin-C/electricitymap_twitter#3]
Hey Robin,

I'm a software engineer from Electricity Maps :) 
It's still cool to see the engagement your bot is creating and it's a great way to share the data more broadly!

With that said, we also frequently see people misunderstanding the tweet and not realising the carbon intensity shown is for one specific hour. It would be great if you could somehow clarify that in the tweet?

**Comment by Robin-C** [comment]
completed: https://github.com/Robin-C/electricitymap_twitter/pull/4

**Comment by Robin-C** [comment]
completed https://github.com/Robin-C/electricitymap_twitter/pull/4
